[book]
title = "impl Rust for ESP32"
authors = ["ImplFerris"]
language = "en"
src = "src"

[output.html]
git-repository-url = "https://github.com/ImplFerris/esp32-book"
cname = "esp32.implrust.com"
preferred-dark-theme = "ayu"
default-theme = "dark"
mathjax-support = true


# Don't show table of contents for entire page in the navigation bar
# Pretty confusing to look at the chapter 
sidebar-header-nav = false

additional-css = ["theme/css/custom.css"]

# [output.html.playground]
# editable = true

[output.html.fold]
enable = true
level = 1     # the depth to start folding
